PREFIX schema: <https://schema.org/> 
PREFIX bio: <https://bioschemas.org/> # tmp
PREFIX wikibase: <http://wikiba.se/ontology#>

CONSTRUCT {
?cellular_component wdt:P31 wd:Q5058355.
?cellular_component wdt:P361 ?part_of.
?cellular_component wdt:P527 ?has_part.
}


WHERE {
{?cellular_component wdt:P31/wdt:P279* wd:Q5058355}
UNION {?cellular_component wdt:P31/wdt:P279* wd:Q5058355. ?cellular_component wdt:P361 ?part_of.}
UNION {?cellular_component wdt:P31/wdt:P279* wd:Q5058355. ?cellular_component wdt:P527 ?has_part.}

SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}