PREFIX schema: <https://schema.org/> 
PREFIX wikibase: <http://wikiba.se/ontology#>

CONSTRUCT {
?molecular_function wdt:P31 wd:Q14860489.
?molecular_function wdt:P361 ?part_of.
?molecular_function wdt:P527 ?has_part.
}


WHERE {
{?molecular_function wdt:P31/wdt:P279* wd:Q14860489}
UNION {?molecular_function wdt:P31/wdt:P279* wd:Q14860489. ?molecular_function wdt:P361 ?part_of.}
UNION {?molecular_function wdt:P31/wdt:P279* wd:Q14860489. ?molecular_function wdt:P527 ?has_part.}

SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
